Main.class: Hunger.class Health.class Energy.class Temper.class Attribute.class PetPet.class Liger.class BOwl.class Main.java
	javac Main.java
Hunger.class: Hunger.java
	javac Hunger.java
Energy.class: Energy.java
	javac Energy.java
Health.class: Health.java
	javac Health.java
Temper.class: Temper.java
	javac Temper.java
Liger.class: Liger.java
	javac Liger.java
BOwl.class: BOwl.java
	javac BOwl.java
Attribute.class: Attribute.java
	javac Attribute.java
PetPet.class: PetPet.java
	javac PetPet.java

run: Main.class 
	java Main
clean: 
	rm *.class
