ATM.class: ATM.java User.class Checking.class Savings.class Admin.class
	javac ATM.java
User.class: User.java
	javac User.java
Admin.class: Admin.java
	javac Admin.java
Checking.class: Checking.java
	javac Checking.java
Savings.class: Savings.java
	javac Savings.java
run: ATM.class
	java ATM
clean:
	rm *.class
vim: 
	vim ATM.java		

